/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesRealEstateRouteImport } from './routes/services.real-estate'
import { Route as ServicesBusinessFormationRouteImport } from './routes/services.business-formation'
import { Route as ServicesAssetRecoveryRouteImport } from './routes/services.asset-recovery'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRealEstateRoute = ServicesRealEstateRouteImport.update({
  id: '/services/real-estate',
  path: '/services/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessFormationRoute =
  ServicesBusinessFormationRouteImport.update({
    id: '/services/business-formation',
    path: '/services/business-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAssetRecoveryRoute = ServicesAssetRecoveryRouteImport.update({
  id: '/services/asset-recovery',
  path: '/services/asset-recovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/asset-recovery': typeof ServicesAssetRecoveryRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/seo': typeof ServicesSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/asset-recovery': typeof ServicesAssetRecoveryRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/seo': typeof ServicesSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/asset-recovery': typeof ServicesAssetRecoveryRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/real-estate': typeof ServicesRealEstateRoute
  '/services/seo': typeof ServicesSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/services/asset-recovery'
    | '/services/business-formation'
    | '/services/real-estate'
    | '/services/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/services/asset-recovery'
    | '/services/business-formation'
    | '/services/real-estate'
    | '/services/seo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/services/asset-recovery'
    | '/services/business-formation'
    | '/services/real-estate'
    | '/services/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesAssetRecoveryRoute: typeof ServicesAssetRecoveryRoute
  ServicesBusinessFormationRoute: typeof ServicesBusinessFormationRoute
  ServicesRealEstateRoute: typeof ServicesRealEstateRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/real-estate': {
      id: '/services/real-estate'
      path: '/services/real-estate'
      fullPath: '/services/real-estate'
      preLoaderRoute: typeof ServicesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-formation': {
      id: '/services/business-formation'
      path: '/services/business-formation'
      fullPath: '/services/business-formation'
      preLoaderRoute: typeof ServicesBusinessFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/asset-recovery': {
      id: '/services/asset-recovery'
      path: '/services/asset-recovery'
      fullPath: '/services/asset-recovery'
      preLoaderRoute: typeof ServicesAssetRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesAssetRecoveryRoute: ServicesAssetRecoveryRoute,
  ServicesBusinessFormationRoute: ServicesBusinessFormationRoute,
  ServicesRealEstateRoute: ServicesRealEstateRoute,
  ServicesSeoRoute: ServicesSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
